/**:
  ros__parameters:
    use_sim_time: true

amcl:
  ros__parameters:
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "scan"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    laser_model_type: "likelihood_field"
    min_particles: 500
    max_particles: 2000
    tf_broadcast: true
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1
    transform_tolerance: 2.0
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    set_initial_pose: true
    transform_tolerance: 1.0
    first_map_only: false

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

controller_server:
  ros__parameters:
    controller_frequency: 5.0
    odom_topic: "odometry/filtered"
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.35
      yaw_goal_tolerance: 0.35
      stateful: true

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      publish_cost_grid_pc: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.5
      max_vel_y: 0.0
      max_vel_theta: 0.8
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: 0.0
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -0.5
      decel_lim_y: 0.0
      decel_lim_theta: -1.0
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.5
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      Oscillation.scale: 32.0
      ObstacleFootprint.scale: 0.05
      ObstacleFootprint.max_scaling_factor: 0.2
      ObstacleFootprint.scaling_speed: 0.25

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      robot_radius: 0.15
      transform_tolerance: 2.0
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 2.5

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      track_unknown_space: true
      robot_radius: 0.15
      resolution: 0.05
      width: 100
      height: 100
      origin_x: -50.0
      origin_y: -50.0
      robot_radius: 0.2
      transform_tolerance: 2.0
      tf_buffer_duration: 30.0
      always_send_full_costmap: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 2.5

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.5]
    min_velocity: [-0.5, 0.0, -2.5]
    max_accel: [0.3, 0.0, 3.2]
    max_decel: [-0.5, 0.0, -3.2]
    odom_topic: "odometry/filtered"
    velocity_timeout: 1.0

slam_toolbox:
  ros__parameters:
    # General Parameters
    map_frame: map
    base_frame: base_footprint
    odom_frame: odom
    scan_topic: /scan
    
    # SLAM Modes: mapping, localization, or offline_mapping
    mode: mapping
    
    # Map Management
    map_file_name: ""
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true
    
    # Scan Processing
    max_laser_range: 8.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    
    # Map Update Parameters
    resolution: 0.05
    map_update_interval: 2.0
    transform_publish_period: 0.02
    update_factor: 4.0
    
    # Loop Closure
    enable_interactive_mode: false
    loop_search_maximum_distance: 10.0
    
    # Map Builder Parameters
    map_builder:
      use_scan_matching: true
      use_scan_barycenter: true
      resolution: 0.05
      maximum_laser_range: 20.0
      minimum_range: 0.5
      smear_deviation: 0.03