<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Wheel Macro -->
	<xacro:macro name="wheel" params="parent_prefix wheel_prefix reflect wheel_type *joint_pose">
		<joint name="${wheel_prefix}_wheel_joint" type="continuous">
			<parent link="${parent_prefix}" />
			<child link="${wheel_prefix}_wheel" />
			<xacro:insert_block name="joint_pose" />

			<axis xyz="0 ${reflect*1} 0">
				<limit>
					<effort>100</effort>
				</limit>
			</axis>

		</joint>

		<link name="${wheel_prefix}_wheel">
			<visual name="${wheel_prefix}_wheel_visual">
				<origin xyz="0 ${wheel_length/2} 0" rpy="0 0 0" />
				<geometry>
					<mesh
						filename="package://arap_robot_description/meshes/wheels/${wheel_type}/${wheel_type}.dae" />
				</geometry>
			</visual>
			<collision name="${wheel_prefix}_wheel_collision">
				<origin xyz="0 ${wheel_length/2} 0" rpy="0 0 0" />
				<geometry>
					<mesh
						filename="package://arap_robot_description/meshes/wheels/${wheel_type}/${wheel_type}.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial prefix="${wheel_prefix}_wheel" mass="${wheel_mass}"
				radius="${wheel_radius}" length="${wheel_radius}">
				<origin xyz="0 ${wheel_radius/2} 0" rpy="${M_PI/2} 0 0" />
			</xacro:cylinder_inertial>
		</link>

		<gazebo reference="${wheel_prefix}_wheel">
			<collision>
				<surface>
					<friction>
						<ode>
							<mu>1.0</mu>
							<mu2>1.0</mu2>
							<kp>100.0</kp>
							<kd>1.0</kd>
							<minDepth>0.01</minDepth>
							<fdir1>1 0 0</fdir1>
							<maxContacts value="64" />
						</ode>
					</friction>
				</surface>
			</collision>
		</gazebo>

	</xacro:macro>

	<!-- Wheel Setup Macro -->
	<xacro:macro name="wheel_setup" params="wheel_type config">
		<xacro:property name="front_left_xyz"
			value="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" />
		<xacro:property name="front_right_xyz"
			value="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" />
		<xacro:property name="rear_left_xyz"
			value="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" />
		<xacro:property name="rear_right_xyz"
			value="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" />
		<xacro:property name="left_rpy" value="0 0 0" />
		<xacro:property name="right_rpy" value="${M_PI} 0 0" />

		<!-- Front Wheels -->
		<xacro:wheel wheel_prefix="front_left" parent_prefix="base_link" reflect="1"
			wheel_type="${wheel_type}">
			<origin xyz="${front_left_xyz}" rpy="${left_rpy}" />
		</xacro:wheel>
		<xacro:wheel wheel_prefix="front_right" parent_prefix="base_link" reflect="-1"
			wheel_type="${wheel_type}">
			<origin xyz="${front_right_xyz}" rpy="${right_rpy}" />
		</xacro:wheel>

		<!-- Rear Wheels -->
		<xacro:wheel wheel_prefix="rear_left" parent_prefix="base_link" reflect="1"
			wheel_type="${wheel_type}">
			<origin xyz="${rear_left_xyz}" rpy="${left_rpy}" />
		</xacro:wheel>
		<xacro:wheel wheel_prefix="rear_right" parent_prefix="base_link" reflect="-1"
			wheel_type="${wheel_type}">
			<origin xyz="${rear_right_xyz}" rpy="${right_rpy}" />
		</xacro:wheel>
	</xacro:macro>
</robot>